// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh7K7ibs7c1lb4kG5EfmFFdj8wOlHnlj4',
    appId: '1:954251561835:web:25fdb646f541792f131a2e',
    messagingSenderId: '954251561835',
    projectId: 'studentloginbackend-2ba0a',
    authDomain: 'studentloginbackend-2ba0a.firebaseapp.com',
    storageBucket: 'studentloginbackend-2ba0a.firebasestorage.app',
    measurementId: 'G-9QV210RHNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHYV-bqcx2wrP5sRi7ovVHFfF0eDPgSvk',
    appId: '1:954251561835:android:5f171dca542362ac131a2e',
    messagingSenderId: '954251561835',
    projectId: 'studentloginbackend-2ba0a',
    storageBucket: 'studentloginbackend-2ba0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5BdvxHxqT3g9zRUXPe53Vktrc14jSiY8',
    appId: '1:954251561835:ios:1bdaea166c26aa47131a2e',
    messagingSenderId: '954251561835',
    projectId: 'studentloginbackend-2ba0a',
    storageBucket: 'studentloginbackend-2ba0a.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5BdvxHxqT3g9zRUXPe53Vktrc14jSiY8',
    appId: '1:954251561835:ios:1bdaea166c26aa47131a2e',
    messagingSenderId: '954251561835',
    projectId: 'studentloginbackend-2ba0a',
    storageBucket: 'studentloginbackend-2ba0a.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh7K7ibs7c1lb4kG5EfmFFdj8wOlHnlj4',
    appId: '1:954251561835:web:35725a4c5b0c1323131a2e',
    messagingSenderId: '954251561835',
    projectId: 'studentloginbackend-2ba0a',
    authDomain: 'studentloginbackend-2ba0a.firebaseapp.com',
    storageBucket: 'studentloginbackend-2ba0a.firebasestorage.app',
    measurementId: 'G-DR16RWD2X5',
  );
}
